name: Collect commit info and send to slack

on:
  push:
    branches:
      - '*'

jobs:
  commit-info:
    name: Send commit info to slack
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository and checkout
      uses: actions/checkout@v2

    - name: Collect commit info
      run: |
        echo "Commit Message  : ${{ github.event.head_commit.message }}"
        echo "Commit SHA      : ${{ github.event.head_commit.id }}"
        echo "User Name       : ${{ github.event.head_commit.author.name }}"
        echo "Repository Name : ${{ github.repository }}"
        echo "Branch Name     : ${{ github.ref }}"
        echo "Runner Name     : ${{ runner.hostname }}"
        echo "ENV             : ${{ toJson(env) }}"

